config/routes.rb
Cetifarma::Application.routes.draw do
  root  'static_pages#home'
  match '/codigo',    to: 'static_pages#codigo',    via: 'get'
  resources :adherentes
  resources :users

  

end

app/models/adherente.rb
class Adherente < ActiveRecord::Base
	belongs_to :user
	validates :nombre, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
		has_many :adherentes


		validates :name, :password,  presence: true, length: { maximum: 150 }
		validates :password, length: { minimum: 6 }
		
		VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  		validates :email, format: { with: VALID_EMAIL_REGEX },
  							uniqueness: true,
  							presence: true
		
		before_save { email.downcase! }

		has_secure_password

		
end

app/controllers/adherentes_controller.rb
class AdherentesController < ApplicationController
  before_action :set_adherente, only: [:show, :edit, :update, :destroy]

  # GET /adherentes
  # GET /adherentes.json
  def index
    @adherentes = Adherente.all
  end

  # GET /adherentes/1
  # GET /adherentes/1.json
  def show
  end

  # GET /adherentes/new
  def new
    @adherente = Adherente.new
  end

  # GET /adherentes/1/edit
  def edit
  end

  # POST /adherentes
  # POST /adherentes.json
  def create
    @adherente = Adherente.new(adherente_params)

    respond_to do |format|
      if @adherente.save
        format.html { redirect_to @adherente, notice: 'Adherente was successfully created.' }
        format.json { render action: 'show', status: :created, location: @adherente }
      else
        format.html { render action: 'new' }
        format.json { render json: @adherente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adherentes/1
  # PATCH/PUT /adherentes/1.json
  def update
    respond_to do |format|
      if @adherente.update(adherente_params)
        format.html { redirect_to @adherente, notice: 'Adherente was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @adherente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adherentes/1
  # DELETE /adherentes/1.json
  def destroy
    @adherente.destroy
    respond_to do |format|
      format.html { redirect_to adherentes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adherente
      @adherente = Adherente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adherente_params
      params.require(:adherente).permit(:nombre, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@adherentes = Adherente.all
  end

  def codigo
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/adherentes_helper.rb
module AdherentesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Cetifarma"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/adherentes/_form.html.erb
<%= form_for(@adherente) do |f| %>
  <% if @adherente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adherente.errors.count, "error") %> prohibited this adherente from being saved:</h2>

      <ul>
      <% @adherente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adherentes/edit.html.erb
<h1>Editing adherente</h1>

<%= render 'form' %>

<%= link_to 'Show', @adherente %> |
<%= link_to 'Back', adherentes_path %>

app/views/adherentes/index.html.erb
<h1>Listing adherentes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @adherentes.each do |adherente| %>
      <tr>
        <td><%= adherente.nombre %></td>
        <td><%= adherente.user_id %></td>
        <td><%= link_to 'Show', adherente %></td>
        <td><%= link_to 'Edit', edit_adherente_path(adherente) %></td>
        <td><%= link_to 'Destroy', adherente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adherente', new_adherente_path %>

app/views/adherentes/new.html.erb
<h1>New adherente</h1>

<%= render 'form' %>

<%= link_to 'Back', adherentes_path %>

app/views/adherentes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @adherente.nombre %>
</p>

<p>
  <strong>User:</strong>
  <%= @adherente.user_id %>
</p>

<%= link_to 'Edit', edit_adherente_path(@adherente) %> |
<%= link_to 'Back', adherentes_path %>

app/views/layouts/_footer.html.erb
<div id="footer" class="fixed-bottom">
	<div class="container">
	  <center>
	    <p>
	        Cetifarma ® 2013
	    </p>
	  </center>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar  navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button style="z-index:100" type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Cetifarma</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav pull-right">
          
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Códigos<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Capitulo 1", codigo_path %></li>
            <li><%= link_to "Capitulo 2", codigo_path %></li>
            <li><%= link_to "Capitulo 3", codigo_path %></li>
            <li><%= link_to "Capitulo 4", codigo_path %></li>
          </ul>
        </li>
        <li class="active"><%= link_to "Home", root_path %></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag   "application", media: "all"%>
  
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll">

	<%= render 'layouts/header' %>

    <div id="wrap">
      <div class="container">
      	<% flash.each do |key, value| %>
        	<div class="alert alert-<%= key %>"><%= value %></div>
      	<% end %>
        <div class="row">
          	<%= yield %>
          </div>	
		</div>
	</div>
	<%= render 'layouts/footer' %>

     <%= javascript_include_tag "application"%> 
   
</body>

</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      La forma contiene <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/codigo.html.erb
<% provide(:title, 'Código') %>
<h1>Código Cetifarma</h1>
<p>Find me in app/views/static_pages/codigo.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="col-md-3">
	<%= render 'static_pages/home/homesidebar' %>
</div>
<div class="col-md-9">
	<%= render 'static_pages/home/carouselbanner' %>
	<div class="row">
		          
		<div class="col-md-6">
			<%= render 'static_pages/home/servicios' %>
		</div>
		<div class="col-md-6">
			<%= render 'static_pages/home/documentos' %>
		</div>
	</div>
	<div class="row">              
		<div class="col-md-12">
			<%= render 'static_pages/home/adherentes' %>
		</div>
	</div>
	<div class="row">
	              
	  	<div class="col-md-12">
			<%= render 'static_pages/home/consejoeticatransparencia' %>
		</div>
	</div>
</div>

app/views/static_pages/home/_adherentes.html.erb
<h2 id="adherentes"><img src="assets/images/servicios.png" alt="...">Adherentes</h2>
	<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. 
	<div class="well adherentes-well"> 
		<div class="row">
		  	<div class="col-md-6">
		        <ul>
					<% @adherentes.each do |a| %>
						<li><%= a.nombre %></li>
					<% end %>
		        </ul>
	      	</div>
	      	<div class="col-md-6">
				<ul>
					<li>Adherente1</li>
					<li>Adherente2</li>
					<li>Adherente1</li>
					<li>Adherente2</li>
					<li>Adherente1</li>
					<li>Adherente2</li>
					<li>Adherente1</li>
					<li>Adherente2</li>
					<li>Adherente1</li>
					<li>Adherente2</li>
					<li>Adherente2</li>
					<li>Adherente1</li>
					<li>Adherente2</li>
					<li>Adherente1</li>
					<li>Adherente2</li>
				</ul>
	  		</div>
		</div>
	</div>
	<br/><br/>  

app/views/static_pages/home/_carouselbanner.html.erb
<div id="carousel-example-generic" class="carousel slide">
    <!-- Indicadores del carrusel -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

    <!-- Wrapper de carrusel -->
      <div class="carousel-inner">
        <div class="item active">
          <img src="http://placehold.it/1000x400&text=[img]" alt="...">
          <div class="carousel-caption">
            Esta es mi primera imagen
          </div>
        </div>
        <div class="item">
          <img src="http://placehold.it/1000x400&text=[img2]" alt="...">
          <div class="carousel-caption">
            Esta es mi segunda imagen
          </div>
        </div>
        <div class="item">
          <img src="http://placehold.it/1000x400&text=[img3]" alt="...">
          <div class="carousel-caption">
            Esta es mi tercera imagen
          </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
      <span class="icon-prev"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
      <span class="icon-next"></span>
    </a>
</div>

app/views/static_pages/home/_consejoeticatransparencia.html.erb
<h2 id="consejo"><img src="assets/images/servicios.png" alt="...">Consejo de ética y transparencia</h2>
			<p>Nosotros <br/><br/>
			Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
			<br/><br/>
			Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. 
			<br/><br/>
			Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram, anteposuerit litterarum formas humanitatis per seacula quarta decima et quinta decima. Eodem modo typi, qui nunc nobis videntur parum clari, fiant sollemnes in futurum.</p>

app/views/static_pages/home/_documentos.html.erb
<h2 id="documentos"><img src="assets/images/productos.png" alt="...">Documentos</h2>
			<img src="assets/images/documento1.png" alt="Certificado de empresas con prácticas transparentes">

app/views/static_pages/home/_homesidebar.html.erb
<div class="bs-sidebar affix" role="complementary">
    <ul class="nav bs-sidenav">       
      <li class="active"><a href="#servicios">Servicios</a></li>
      <li><a href="#documentos">Documentos</a></li>
      <li><a href="#adherentes">Adherentes</a></li>
      <li><a href="#consejo">Consejo de ética y transparencia</a></li>
    </ul>
    <center>
    <a data-toggle="modal" href="#myModal" class="btn btn-primary btn-lg">Botón videos</a>
  </center>
</div>

app/views/static_pages/home/_servicios.html.erb
<h2 id="servicios"><img src="assets/images/servicios.png" alt="...">Servicios</h2>
			<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>

app/views/users/_form.html.erb
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
    <% end %>
  </div>
</div>
<%= form_for(@user) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>
<br>
    <%= f.label :email %>
    <%= f.text_field :email %>
<br>
    <%= f.label :password %>
    <%= f.password_field :password %>
<br>
  <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
<br><br>
    <%= f.submit "Salvar", class: "btn btn-large btn-primary"  %>

<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
<%= gravatar_for @user %>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>